version: "3.8"

services:
  node_backend:
    container_name: brecha-cero-latam-backend
    image: brecha-cero-latam-backend:0.0.1
    build:
      context: .
    ports:
      - "3001:3001"
    environment:
      - EXTERNAL_PORT=3001
      - MYSQL_DATABASE=brecha-cero-latam-backend_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=krKdU]t{Q_9xY*T(
      - MYSQL_HOST=34.68.51.143
    depends_on:
      - node_db
  node_db:
    container_name: node_db
    image: "mysql:8"
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=brecha-cero-latam-backend_db
    volumes:
      - nps_data:/var/lib/mysql

volumes:
  nps_data: {}
