version: "3.8"

services:
  node_backend:
    container_name: brecha-cero-latam-backend
    image: brecha-cero-latam-backend:0.0.1
    build:
      context: .
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - node_db
  node_db:
    container_name: node_db
    image: "mysql:8"
    ports:
      - "3307:3306"
    env_file:
      - .env
    volumes:
      - nps_data:/var/lib/mysql

volumes:
  nps_data: {}
