CREATE TABLE brechacero.salaries (
    id INT PRIMARY KEY AUTO_INCREMENT,
    net_salary DECIMAL(10, 2) NOT NULL,
    job_role VARCHAR(100) NOT NULL,
    seniority_in_years INT,
    tech_stack JSON,
    company_size VARCHAR(50),
    location VARCHAR(100),
    english BOOLEAN,
    max_education_level VARCHAR(100),
    working_hours_per_week INT
);

INSERT INTO brechacero.salaries (net_salary, job_role, seniority_in_years, tech_stack, company_size, location, english, max_education_level, working_hours_per_week)
VALUES 
    (28000.00, 'Desarrollador/a Frontend', 2, '["HTML", "CSS", "JavaScript"]', 'Pequeña', 'Ciudad de México', TRUE, 'Licenciatura', 40),
    (38000.00, 'Ingeniero/a de datos', 4, '["Python", "Spark", "Hadoop"]', 'Grande', 'Guadalajara', TRUE, 'Maestría', 45),
    (18000.00, 'Diseñador/a gráfico/a', 3, '["Adobe Photoshop", "Illustrator", "InDesign"]', 'Mediana', 'Monterrey', FALSE, 'Bachillerato', 35),
    (42000.00, 'Arquitecto/a de soluciones', 5, '["AWS", "Azure", "Google Cloud"]', 'Grande', 'Ciudad Juárez', TRUE, 'Maestría', 50),
    (30000.00, 'Desarrollador/a Full Stack', 3, '["JavaScript", "Node.js", "React", "MongoDB"]', 'Mediana', 'Tijuana', TRUE, 'Licenciatura', 42),
    (35000.00, 'Analista/a de sistemas', 4, '["Java", "Spring", "MySQL"]', 'Grande', 'Puebla', TRUE, 'Maestría', 48),
    (22000.00, 'Especialista en marketing digital', 2, '["SEO", "SEM", "Google Analytics"]', 'Pequeña', 'Cancún', TRUE, 'Licenciatura', 40),
    (40000.00, 'Ingeniero/a de software', 6, '["C++", "Python", "Linux"]', 'Grande', 'Hermosillo', TRUE, 'Doctorado', 45),
    (25000.00, 'Analista financiero/a', 4, '["Excel", "SQL", "R"]', 'Mediana', 'Querétaro', FALSE, 'Maestría', 40),
    (32000.00, 'Desarrollador/a móvil', 3, '["Swift", "Kotlin", "Android Studio"]', 'Grande', 'Mérida', TRUE, 'Licenciatura', 45),
    (17000.00, 'Soporte técnico/a', 2, '["Windows", "Linux", "Networking"]', 'Pequeña', 'Chihuahua', FALSE, 'Bachillerato', 38),
    (42000.00, 'Gerente de proyectos', 7, '["PMP", "Scrum", "Project Management"]', 'Grande', 'Aguascalientes', TRUE, 'Maestría', 50),
    (26000.00, 'Analista/a de datos', 3, '["Python", "R", "SQL"]', 'Mediana', 'Toluca', TRUE, 'Licenciatura', 42),
    (30000.00, 'Diseñador/a de experiencia de usuario/a', 4, '["Sketch", "Figma", "Adobe XD"]', 'Mediana', 'Culiacán', TRUE, 'Maestría', 40),
    (36000.00, 'Desarrollador/a Backend', 5, '["Java", "Spring", "Hibernate"]', 'Grande', 'Tuxtla Gutiérrez', TRUE, 'Maestría', 45),
    (18500.00, 'Redactor/a de contenido', 2, '["SEO", "Redacción creativa", "Marketing de contenidos"]', 'Pequeña', 'Durango', TRUE, 'Licenciatura', 40),
    (43000.00, 'Ingeniero/a de sistemas', 6, '["Linux", "Python", "Bash scripting"]', 'Grande', 'Morelia', TRUE, 'Maestría', 50),
    (21000.00, 'Asistente administrativo/a', 3, '["Microsoft Office", "Organización", "Comunicación"]', 'Mediana', 'Tepic', FALSE, 'Bachillerato', 38),
    (35000.00, 'Desarrollador/a Web', 4, '["HTML", "CSS", "JavaScript", "PHP"]', 'Grande', 'Oaxaca', TRUE, 'Maestría', 48),
    (28000.00, 'Desarrollador/a Frontend', 2, '["HTML", "CSS", "JavaScript"]', 'Pequeña', 'Ciudad de México', TRUE, 'Licenciatura', 40),
    (37000.00, 'Ingeniero/a de datos', 4, '["Python", "Spark", "Hadoop"]', 'Grande', 'Guadalajara', TRUE, 'Maestría', 45),
    (19000.00, 'Diseñador/a gráfico/a', 3, '["Adobe Photoshop", "Illustrator", "InDesign"]', 'Mediana', 'Monterrey', FALSE, 'Bachillerato', 35),
    (42000.00, 'Arquitecto/a de soluciones', 5, '["AWS", "Azure", "Google Cloud"]', 'Grande', 'Ciudad Juárez', TRUE, 'Maestría', 50),
    (31000.00, 'Desarrollador/a Full Stack', 3, '["JavaScript", "Node.js", "React", "MongoDB"]', 'Mediana', 'Tijuana', TRUE, 'Licenciatura', 42),
    (36000.00, 'Analista/a de sistemas', 4, '["Java", "Spring", "MySQL"]', 'Grande', 'Puebla', TRUE, 'Maestría', 48),
    (23000.00, 'Especialista en marketing digital', 2, '["SEO", "SEM", "Google Analytics"]', 'Pequeña', 'Cancún', TRUE, 'Licenciatura', 40),
    (42000.00, 'Ingeniero/a de software', 6, '["C++", "Python", "Linux"]', 'Grande', 'Hermosillo', TRUE, 'Doctorado', 45),
    (26000.00, 'Analista financiero/a', 4, '["Excel", "SQL", "R"]', 'Mediana', 'Querétaro', FALSE, 'Maestría', 40),
    (34000.00, 'Desarrollador/a móvil', 3, '["Swift", "Kotlin", "Android Studio"]', 'Grande', 'Mérida', TRUE, 'Licenciatura', 45),
    (18000.00, 'Soporte técnico/a', 2, '["Windows", "Linux", "Networking"]', 'Pequeña', 'Chihuahua', FALSE, 'Bachillerato', 38),
    (41000.00, 'Gerente de proyectos', 7, '["PMP", "Scrum", "Project Management"]', 'Grande', 'Aguascalientes', TRUE, 'Maestría', 50),
    (24000.00, 'Analista/a de datos', 3, '["Python", "R", "SQL"]', 'Mediana', 'Toluca', TRUE, 'Licenciatura', 42),
    (28000.00, 'Diseñador/a de experiencia de usuario/a', 4, '["Sketch", "Figma", "Adobe XD"]', 'Mediana', 'Culiacán', TRUE, 'Maestría', 40),
    (37000.00, 'Desarrollador/a Backend', 5, '["Java", "Spring", "Hibernate"]', 'Grande', 'Tuxtla Gutiérrez', TRUE, 'Maestría', 45),
    (19500.00, 'Redactor/a de contenido', 2, '["SEO", "Redacción creativa", "Marketing de contenidos"]', 'Pequeña', 'Durango', TRUE, 'Licenciatura', 40),
    (43000.00, 'Ingeniero/a de sistemas', 6, '["Linux", "Python", "Bash scripting"]', 'Grande', 'Morelia', TRUE, 'Maestría', 50),
    (22000.00, 'Asistente administrativo/a', 3, '["Microsoft Office", "Organización", "Comunicación"]', 'Mediana', 'Tepic', FALSE, 'Bachillerato', 38),
    (36000.00, 'Desarrollador/a Web', 4, '["HTML", "CSS", "JavaScript", "PHP"]', 'Grande', 'Oaxaca', TRUE, 'Maestría', 48),
    (25000.00, 'Especialista en redes sociales', 3, '["Facebook Ads", "Instagram", "Analytics"]', 'Mediana', 'Xalapa', TRUE, 'Licenciatura', 40),
    (29000.00, 'Desarrollador/a Frontend', 3, '["HTML", "CSS", "JavaScript"]', 'Pequeña', 'Ciudad de México', TRUE, 'Licenciatura', 40),
    (39000.00, 'Ingeniero/a de datos', 5, '["Python", "Spark", "Hadoop"]', 'Grande', 'Guadalajara', TRUE, 'Maestría', 45),
    (20000.00, 'Diseñador/a gráfico/a', 4, '["Adobe Photoshop", "Illustrator", "InDesign"]', 'Mediana', 'Monterrey', FALSE, 'Bachillerato', 35),
    (44000.00, 'Arquitecto/a de soluciones', 6, '["AWS", "Azure", "Google Cloud"]', 'Grande', 'Ciudad Juárez', TRUE, 'Maestría', 50),
    (32000.00, 'Desarrollador/a Full Stack', 4, '["JavaScript", "Node.js", "React", "MongoDB"]', 'Mediana', 'Tijuana', TRUE, 'Licenciatura', 42),
    (38000.00, 'Analista/a de sistemas', 5, '["Java", "Spring", "MySQL"]', 'Grande', 'Puebla', TRUE, 'Maestría', 48),
    (24000.00, 'Especialista en marketing digital', 3, '["SEO", "SEM", "Google Analytics"]', 'Pequeña', 'Cancún', TRUE, 'Licenciatura', 40),
    (44000.00, 'Ingeniero/a de software', 7, '["C++", "Python", "Linux"]', 'Grande', 'Hermosillo', TRUE, 'Doctorado', 45),
    (27000.00, 'Analista financiero/a', 5, '["Excel", "SQL", "R"]', 'Mediana', 'Querétaro', FALSE, 'Maestría', 40),
    (36000.00, 'Desarrollador/a móvil', 4, '["Swift", "Kotlin", "Android Studio"]', 'Grande', 'Mérida', TRUE, 'Licenciatura', 45),
    (19000.00, 'Soporte técnico/a', 3, '["Windows", "Linux", "Networking"]', 'Pequeña', 'Chihuahua', FALSE, 'Bachillerato', 38),
    (43000.00, 'Gerente de proyectos', 8, '["PMP", "Scrum", "Project Management"]', 'Grande', 'Aguascalientes', TRUE, 'Maestría', 50),
    (26000.00, 'Analista/a de datos', 4, '["Python", "R", "SQL"]', 'Mediana', 'Toluca', TRUE, 'Licenciatura', 42),
    (30000.00, 'Diseñador/a de experiencia de usuario/a', 5, '["Sketch", "Figma", "Adobe XD"]', 'Mediana', 'Culiacán', TRUE, 'Maestría', 40),
    (39000.00, 'Desarrollador/a Backend', 6, '["Java", "Spring", "Hibernate"]', 'Grande', 'Tuxtla Gutiérrez', TRUE, 'Maestría', 45),
    (20500.00, 'Redactor/a de contenido', 3, '["SEO", "Redacción creativa", "Marketing de contenidos"]', 'Pequeña', 'Durango', TRUE, 'Licenciatura', 40),
    (46000.00, 'Ingeniero/a de sistemas', 7, '["Linux", "Python", "Bash scripting"]', 'Grande', 'Morelia', TRUE, 'Maestría', 50),
    (23000.00, 'Asistente administrativo/a', 4, '["Microsoft Office", "Organización", "Comunicación"]', 'Mediana', 'Tepic', FALSE, 'Bachillerato', 38),
    (38000.00, 'Desarrollador/a Web', 5, '["HTML", "CSS", "JavaScript", "PHP"]', 'Grande', 'Oaxaca', TRUE, 'Maestría', 48),
	(30000.00, 'Desarrollador/a Frontend', 3, '["HTML", "CSS", "JavaScript"]', 'Pequeña', 'Ciudad de México', TRUE, 'Licenciatura', 40),
    (40000.00, 'Ingeniero/a de datos', 5, '["Python", "Spark", "Hadoop"]', 'Grande', 'Guadalajara', TRUE, 'Maestría', 45),
    (21000.00, 'Diseñador/a gráfico/a', 4, '["Adobe Photoshop", "Illustrator", "InDesign"]', 'Mediana', 'Monterrey', FALSE, 'Bachillerato', 35),
    (46000.00, 'Arquitecto/a de soluciones', 6, '["AWS", "Azure", "Google Cloud"]', 'Grande', 'Ciudad Juárez', TRUE, 'Maestría', 50),
    (34000.00, 'Desarrollador/a Full Stack', 4, '["JavaScript", "Node.js", "React", "MongoDB"]', 'Mediana', 'Tijuana', TRUE, 'Licenciatura', 42),
    (40000.00, 'Analista/a de sistemas', 5, '["Java", "Spring", "MySQL"]', 'Grande', 'Puebla', TRUE, 'Maestría', 48),
    (25000.00, 'Especialista en marketing digital', 3, '["SEO", "SEM", "Google Analytics"]', 'Pequeña', 'Cancún', TRUE, 'Licenciatura', 40),
    (46000.00, 'Ingeniero/a de software', 7, '["C++", "Python", "Linux"]', 'Grande', 'Hermosillo', TRUE, 'Doctorado', 45),
    (29000.00, 'Analista financiero/a', 5, '["Excel", "SQL", "R"]', 'Mediana', 'Querétaro', FALSE, 'Maestría', 40),
    (38000.00, 'Desarrollador/a móvil', 4, '["Swift", "Kotlin", "Android Studio"]', 'Grande', 'Mérida', TRUE, 'Licenciatura', 45),
    (20000.00, 'Soporte técnico/a', 3, '["Windows", "Linux", "Networking"]', 'Pequeña', 'Chihuahua', FALSE, 'Bachillerato', 38),
    (45000.00, 'Gerente de proyectos', 8, '["PMP", "Scrum", "Project Management"]', 'Grande', 'Aguascalientes', TRUE, 'Maestría', 50),
    (27000.00, 'Analista/a de datos', 4, '["Python", "R", "SQL"]', 'Mediana', 'Toluca', TRUE, 'Licenciatura', 42),
    (32000.00, 'Diseñador/a de experiencia de usuario/a', 5, '["Sketch", "Figma", "Adobe XD"]', 'Mediana', 'Culiacán', TRUE, 'Maestría', 40),
    (41000.00, 'Desarrollador/a Backend', 6, '["Java", "Spring", "Hibernate"]', 'Grande', 'Tuxtla Gutiérrez', TRUE, 'Maestría', 45),
    (21500.00, 'Redactor/a de contenido', 3, '["SEO", "Redacción creativa", "Marketing de contenidos"]', 'Pequeña', 'Durango', TRUE, 'Licenciatura', 40),
    (47000.00, 'Ingeniero/a de sistemas', 7, '["Linux", "Python", "Bash scripting"]', 'Grande', 'Morelia', TRUE, 'Maestría', 50),
    (24000.00, 'Asistente administrativo/a', 4, '["Microsoft Office", "Organización", "Comunicación"]', 'Mediana', 'Tepic', FALSE, 'Bachillerato', 38),
    (31000.00, 'Desarrollador/a Frontend', 3, '["HTML", "CSS", "JavaScript"]', 'Pequeña', 'Ciudad de México', TRUE, 'Licenciatura', 40),
    (42000.00, 'Ingeniero/a de datos', 5, '["Python", "Spark", "Hadoop"]', 'Grande', 'Guadalajara', TRUE, 'Maestría', 45),
    (22000.00, 'Diseñador/a gráfico/a', 4, '["Adobe Photoshop", "Illustrator", "InDesign"]', 'Mediana', 'Monterrey', FALSE, 'Bachillerato', 35),
    (48000.00, 'Arquitecto/a de soluciones', 6, '["AWS", "Azure", "Google Cloud"]', 'Grande', 'Ciudad Juárez', TRUE, 'Maestría', 50),
    (35000.00, 'Desarrollador/a Full Stack', 4, '["JavaScript", "Node.js", "React", "MongoDB"]', 'Mediana', 'Tijuana', TRUE, 'Licenciatura', 42),
    (41000.00, 'Analista/a de sistemas', 5, '["Java", "Spring", "MySQL"]', 'Grande', 'Puebla', TRUE, 'Maestría', 48),
    (26000.00, 'Especialista en marketing digital', 3, '["SEO", "SEM", "Google Analytics"]', 'Pequeña', 'Cancún', TRUE, 'Licenciatura', 40),
    (48000.00, 'Ingeniero/a de software', 7, '["C++", "Python", "Linux"]', 'Grande', 'Hermosillo', TRUE, 'Doctorado', 45),
    (30000.00, 'Analista financiero/a', 5, '["Excel", "SQL", "R"]', 'Mediana', 'Querétaro', FALSE, 'Maestría', 40),
    (39000.00, 'Desarrollador/a móvil', 4, '["Swift", "Kotlin", "Android Studio"]', 'Grande', 'Mérida', TRUE, 'Licenciatura', 45),
    (21000.00, 'Soporte técnico/a', 3, '["Windows", "Linux", "Networking"]', 'Pequeña', 'Chihuahua', FALSE, 'Bachillerato', 38),
    (47000.00, 'Gerente de proyectos', 8, '["PMP", "Scrum", "Project Management"]', 'Grande', 'Aguascalientes', TRUE, 'Maestría', 50),
    (28000.00, 'Analista/a de datos', 4, '["Python", "R", "SQL"]', 'Mediana', 'Toluca', TRUE, 'Licenciatura', 42),
    (33000.00, 'Diseñador/a de experiencia de usuario/a', 5, '["Sketch", "Figma", "Adobe XD"]', 'Mediana', 'Culiacán', TRUE, 'Maestría', 40),
    (42000.00, 'Desarrollador/a Backend', 6, '["Java", "Spring", "Hibernate"]', 'Grande', 'Tuxtla Gutiérrez', TRUE, 'Maestría', 45),
    (22500.00, 'Redactor/a de contenido', 3, '["SEO", "Redacción creativa", "Marketing de contenidos"]', 'Pequeña', 'Durango', TRUE, 'Licenciatura', 40),
    (49000.00, 'Ingeniero/a de sistemas', 7, '["Linux", "Python", "Bash scripting"]', 'Grande', 'Morelia', TRUE, 'Maestría', 50),
    (25000.00, 'Asistente administrativo/a', 4, '["Microsoft Office", "Organización", "Comunicación"]', 'Mediana', 'Tepic', FALSE, 'Bachillerato', 38),
    (41000.00, 'Desarrollador/a Web', 5, '["HTML", "CSS", "JavaScript", "PHP"]', 'Grande', 'Oaxaca', TRUE, 'Maestría', 48),
    (28000.00, 'Especialista en redes sociales', 4, '["Facebook Ads", "Instagram", "Analytics"]', 'Mediana', 'Xalapa', TRUE, 'Licenciatura', 40),
    (33000.00, 'Ingeniero/a de datos', 3, '["Python", "Spark", "Hadoop"]', 'Pequeña', 'Ciudad de México', TRUE, 'Licenciatura', 40),
    (44000.00, 'Diseñador/a gráfico/a', 5, '["Adobe Photoshop", "Illustrator", "InDesign"]', 'Grande', 'Guadalajara', TRUE, 'Maestría', 45),
    (24000.00, 'Arquitecto/a de soluciones', 4, '["AWS", "Azure", "Google Cloud"]', 'Mediana', 'Monterrey', FALSE, 'Bachillerato', 35),
    (52000.00, 'Desarrollador/a Full Stack', 6, '["JavaScript", "Node.js", "React", "MongoDB"]', 'Grande', 'Ciudad Juárez', TRUE, 'Maestría', 50),
    (38000.00, 'Analista/a de sistemas', 4, '["Java", "Spring", "MySQL"]', 'Mediana', 'Tijuana', TRUE, 'Licenciatura', 42),
    (44000.00, 'Especialista en marketing digital', 5, '["SEO", "SEM", "Google Analytics"]', 'Grande', 'Puebla', TRUE, 'Licenciatura', 48),
    (28000.00, 'Ingeniero/a de software', 3, '["C++", "Python", "Linux"]', 'Pequeña', 'Cancún', TRUE, 'Doctorado', 40),
    (52000.00, 'Analista financiero/a', 7, '["Excel", "SQL", "R"]', 'Grande', 'Hermosillo', FALSE, 'Maestría', 45),
    (33000.00, 'Desarrollador/a móvil', 5, '["Swift", "Kotlin", "Android Studio"]', 'Mediana', 'Querétaro', TRUE, 'Licenciatura', 42),
    (42000.00, 'Soporte técnico/a', 4, '["Windows", "Linux", "Networking"]', 'Grande', 'Mérida', FALSE, 'Bachillerato', 45),
    (23000.00, 'Gerente de proyectos', 3, '["PMP", "Scrum", "Project Management"]', 'Pequeña', 'Chihuahua', TRUE, 'Maestría', 38),
    (50000.00, 'Analista/a de datos', 8, '["Python", "R", "SQL"]', 'Grande', 'Aguascalientes', TRUE, 'Licenciatura', 50),
    (30000.00, 'Diseñador/a de experiencia de usuario/a', 4, '["Sketch", "Figma", "Adobe XD"]', 'Mediana', 'Toluca', TRUE, 'Maestría', 42),
    (35000.00, 'Desarrollador/a Backend', 5, '["Java", "Spring", "Hibernate"]', 'Mediana', 'Culiacán', TRUE, 'Maestría', 40),
    (44000.00, 'Redactor/a de contenido', 6, '["SEO", "Redacción creativa", "Marketing de contenidos"]', 'Grande', 'Tuxtla Gutiérrez', TRUE, 'Licenciatura', 45),
    (24500.00, 'Ingeniero/a de sistemas', 3, '["Linux", "Python", "Bash scripting"]', 'Pequeña', 'Durango', TRUE, 'Maestría', 40),
    (51000.00, 'Asistente administrativo/a', 7, '["Microsoft Office", "Organización", "Comunicación"]', 'Grande', 'Morelia', FALSE, 'Bachillerato', 50),
    (26000.00, 'Desarrollador/a Web', 4, '["HTML", "CSS", "JavaScript", "PHP"]', 'Mediana', 'Tepic', TRUE, 'Maestría', 38),
    (42000.00, 'Especialista en redes sociales', 5, '["Facebook Ads", "Instagram", "Analytics"]', 'Grande', 'Oaxaca', TRUE, 'Licenciatura', 48)
    ;
    
    